version: '3.7'

networks:
  trino_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  mysql-db:
  warehouse:

services:
  # MySQL como metastore de Hive
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: metastore_db
      MYSQL_USER: hive
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      trino_network:
        ipv4_address: 172.21.0.7

  # Metastore de Hive
  metastore:
    image: apache/hive:4.0.1
    depends_on:
      - mysql
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: mysql
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=com.mysql.cj.jdbc.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:mysql://mysql:3306/metastore_db?useSSL=false
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
    ports:
      - '9083:9083'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./hive/conf/mysql-connector-j-8.0.33.jar:/opt/hive/lib/mysql.jar  # ⬅ Conector MySQL
    networks:
      trino_network:
        ipv4_address: 172.21.0.8

  # HiveServer2
  hiveserver2:
    image: apache/hive:4.0.1
    restart: unless-stopped
    depends_on:
      - metastore
    container_name: hiveserver2
    hostname: hiveserver2
    environment:
      DB_DRIVER: mysql
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./hive/conf/mysql-connector-j-8.0.33.jar:/opt/hive/lib/mysql.jar  # ⬅ Conector MySQL
    command: ["/bin/bash", "-c", "chmod -R 777 /user/hive/data/warehouse && /opt/hive/bin/hive --service hiveserver2"]
    networks:
      trino_network:
        ipv4_address: 172.21.0.9

  # Trino
  trino:
    image: trinodb/trino:472
    restart: unless-stopped
    container_name: trino
    hostname: trino
    user: root
    environment:
      - TRINO_CONFIG_DIR=/etc/trino
    volumes:
      - ./trino/conf:/etc/trino
      - ./trino/conf/catalog:/etc/trino/catalog  # <-- MONTA EL CONECTOR DE HIVE
      - warehouse:/opt/hive/data/warehouse
      - ./hive/conf/hive-site.xml:/etc/trino/hive-site.xml # <-- Copia hive-site.xml directamente

    depends_on:
      - hiveserver2
    ports:
      - '8080:8080'
    
    networks:
      trino_network:
        ipv4_address: 172.21.0.10
