version: '3.7'

networks:
  hive_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  pg-db:
  warehouse:


services:
  # PostgreSQL como metastore de Hive
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metastore_db
    ports:
      - '5432:5432'
    volumes:
      - pg-db:/var/lib/postgresql/data
    networks:
      hive_network:
        ipv4_address: 172.21.0.7

  # Metastore de Hive
  metastore:
    image: apache/hive:4.0.1
    depends_on:
      - postgres
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password'
      HADOOP_CLASSPATH: /opt/hive/lib/postgresql.jar
    ports:
      - '9083:9083'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./hive/conf/postgresql-42.3.8.jar:/opt/hive/lib/postgresql.jar # ⬅ Conector PostgreSQL
    networks:
      hive_network:
        ipv4_address: 172.21.0.8

  # HiveServer2
  hiveserver2:
    image: apache/hive:4.0.1
    restart: unless-stopped
    depends_on:
      - metastore
    container_name: hiveserver2
    hostname: hiveserver2
    environment:
      DB_DRIVER: postgres
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./hive/conf/postgresql-42.3.8.jar:/opt/hive/lib/postgresql.jar # ⬅ Conector PostgreSQL
    command: [ "/bin/bash", "-c", "/opt/hive/bin/hive --service hiveserver2" ]
    networks:
      hive_network:
        ipv4_address: 172.21.0.9
